<?php


/**
 * This class defines the structure of the 'mensaje' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Dec  5 22:27:06 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class MensajeTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.MensajeTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('mensaje');
		$this->setPhpName('Mensaje');
		$this->setClassname('Mensaje');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('MENSAJE_ID', 'MensajeId', 'INTEGER', true, null, null);
		$this->addForeignKey('DESTINATARIO_ID', 'DestinatarioId', 'INTEGER', 'sf_guard_user', 'ID', true, null, null);
		$this->addForeignKey('REMITENTE_ID', 'RemitenteId', 'INTEGER', 'sf_guard_user', 'ID', true, null, null);
		$this->addColumn('ANONIMO', 'Anonimo', 'INTEGER', true, null, 0);
		$this->addColumn('ASUNTO', 'Asunto', 'VARCHAR', true, 250, null);
		$this->addColumn('MENSAJE', 'Mensaje', 'LONGVARCHAR', false, null, null);
		$this->addColumn('SEND_AT', 'SendAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('sfGuardUserRelatedByDestinatarioId', 'sfGuardUser', RelationMap::MANY_TO_ONE, array('destinatario_id' => 'id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('sfGuardUserRelatedByRemitenteId', 'sfGuardUser', RelationMap::MANY_TO_ONE, array('remitente_id' => 'id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('RespuestaMensaje', 'RespuestaMensaje', RelationMap::ONE_TO_MANY, array('mensaje_id' => 'mensaje_id', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // MensajeTableMap
