<?php


/**
 * Base class that represents a query for the 'red_social_x_perfil' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Wed Dec  8 10:38:18 2010
 *
 * @method     RedSocialXPerfilQuery orderByRedSocialXPerfilId($order = Criteria::ASC) Order by the red_social_x_perfil_id column
 * @method     RedSocialXPerfilQuery orderByUserId($order = Criteria::ASC) Order by the user_id column
 * @method     RedSocialXPerfilQuery orderByRedSocialId($order = Criteria::ASC) Order by the red_social_id column
 * @method     RedSocialXPerfilQuery orderByUrl($order = Criteria::ASC) Order by the url column
 *
 * @method     RedSocialXPerfilQuery groupByRedSocialXPerfilId() Group by the red_social_x_perfil_id column
 * @method     RedSocialXPerfilQuery groupByUserId() Group by the user_id column
 * @method     RedSocialXPerfilQuery groupByRedSocialId() Group by the red_social_id column
 * @method     RedSocialXPerfilQuery groupByUrl() Group by the url column
 *
 * @method     RedSocialXPerfilQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     RedSocialXPerfilQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     RedSocialXPerfilQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     RedSocialXPerfilQuery leftJoinsfGuardUser($relationAlias = null) Adds a LEFT JOIN clause to the query using the sfGuardUser relation
 * @method     RedSocialXPerfilQuery rightJoinsfGuardUser($relationAlias = null) Adds a RIGHT JOIN clause to the query using the sfGuardUser relation
 * @method     RedSocialXPerfilQuery innerJoinsfGuardUser($relationAlias = null) Adds a INNER JOIN clause to the query using the sfGuardUser relation
 *
 * @method     RedSocialXPerfilQuery leftJoinRedSocial($relationAlias = null) Adds a LEFT JOIN clause to the query using the RedSocial relation
 * @method     RedSocialXPerfilQuery rightJoinRedSocial($relationAlias = null) Adds a RIGHT JOIN clause to the query using the RedSocial relation
 * @method     RedSocialXPerfilQuery innerJoinRedSocial($relationAlias = null) Adds a INNER JOIN clause to the query using the RedSocial relation
 *
 * @method     RedSocialXPerfil findOne(PropelPDO $con = null) Return the first RedSocialXPerfil matching the query
 * @method     RedSocialXPerfil findOneOrCreate(PropelPDO $con = null) Return the first RedSocialXPerfil matching the query, or a new RedSocialXPerfil object populated from the query conditions when no match is found
 *
 * @method     RedSocialXPerfil findOneByRedSocialXPerfilId(int $red_social_x_perfil_id) Return the first RedSocialXPerfil filtered by the red_social_x_perfil_id column
 * @method     RedSocialXPerfil findOneByUserId(int $user_id) Return the first RedSocialXPerfil filtered by the user_id column
 * @method     RedSocialXPerfil findOneByRedSocialId(int $red_social_id) Return the first RedSocialXPerfil filtered by the red_social_id column
 * @method     RedSocialXPerfil findOneByUrl(string $url) Return the first RedSocialXPerfil filtered by the url column
 *
 * @method     array findByRedSocialXPerfilId(int $red_social_x_perfil_id) Return RedSocialXPerfil objects filtered by the red_social_x_perfil_id column
 * @method     array findByUserId(int $user_id) Return RedSocialXPerfil objects filtered by the user_id column
 * @method     array findByRedSocialId(int $red_social_id) Return RedSocialXPerfil objects filtered by the red_social_id column
 * @method     array findByUrl(string $url) Return RedSocialXPerfil objects filtered by the url column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseRedSocialXPerfilQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseRedSocialXPerfilQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'RedSocialXPerfil', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new RedSocialXPerfilQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    RedSocialXPerfilQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof RedSocialXPerfilQuery) {
			return $criteria;
		}
		$query = new RedSocialXPerfilQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    RedSocialXPerfil|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = RedSocialXPerfilPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    RedSocialXPerfilQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(RedSocialXPerfilPeer::RED_SOCIAL_X_PERFIL_ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    RedSocialXPerfilQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(RedSocialXPerfilPeer::RED_SOCIAL_X_PERFIL_ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the red_social_x_perfil_id column
	 * 
	 * @param     int|array $redSocialXPerfilId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RedSocialXPerfilQuery The current query, for fluid interface
	 */
	public function filterByRedSocialXPerfilId($redSocialXPerfilId = null, $comparison = null)
	{
		if (is_array($redSocialXPerfilId) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(RedSocialXPerfilPeer::RED_SOCIAL_X_PERFIL_ID, $redSocialXPerfilId, $comparison);
	}

	/**
	 * Filter the query on the user_id column
	 * 
	 * @param     int|array $userId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RedSocialXPerfilQuery The current query, for fluid interface
	 */
	public function filterByUserId($userId = null, $comparison = null)
	{
		if (is_array($userId)) {
			$useMinMax = false;
			if (isset($userId['min'])) {
				$this->addUsingAlias(RedSocialXPerfilPeer::USER_ID, $userId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($userId['max'])) {
				$this->addUsingAlias(RedSocialXPerfilPeer::USER_ID, $userId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(RedSocialXPerfilPeer::USER_ID, $userId, $comparison);
	}

	/**
	 * Filter the query on the red_social_id column
	 * 
	 * @param     int|array $redSocialId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RedSocialXPerfilQuery The current query, for fluid interface
	 */
	public function filterByRedSocialId($redSocialId = null, $comparison = null)
	{
		if (is_array($redSocialId)) {
			$useMinMax = false;
			if (isset($redSocialId['min'])) {
				$this->addUsingAlias(RedSocialXPerfilPeer::RED_SOCIAL_ID, $redSocialId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($redSocialId['max'])) {
				$this->addUsingAlias(RedSocialXPerfilPeer::RED_SOCIAL_ID, $redSocialId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(RedSocialXPerfilPeer::RED_SOCIAL_ID, $redSocialId, $comparison);
	}

	/**
	 * Filter the query on the url column
	 * 
	 * @param     string $url The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RedSocialXPerfilQuery The current query, for fluid interface
	 */
	public function filterByUrl($url = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($url)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $url)) {
				$url = str_replace('*', '%', $url);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(RedSocialXPerfilPeer::URL, $url, $comparison);
	}

	/**
	 * Filter the query by a related sfGuardUser object
	 *
	 * @param     sfGuardUser $sfGuardUser  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RedSocialXPerfilQuery The current query, for fluid interface
	 */
	public function filterBysfGuardUser($sfGuardUser, $comparison = null)
	{
		return $this
			->addUsingAlias(RedSocialXPerfilPeer::USER_ID, $sfGuardUser->getId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the sfGuardUser relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    RedSocialXPerfilQuery The current query, for fluid interface
	 */
	public function joinsfGuardUser($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('sfGuardUser');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'sfGuardUser');
		}
		
		return $this;
	}

	/**
	 * Use the sfGuardUser relation sfGuardUser object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfGuardUserQuery A secondary query class using the current class as primary query
	 */
	public function usesfGuardUserQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinsfGuardUser($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'sfGuardUser', 'sfGuardUserQuery');
	}

	/**
	 * Filter the query by a related RedSocial object
	 *
	 * @param     RedSocial $redSocial  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RedSocialXPerfilQuery The current query, for fluid interface
	 */
	public function filterByRedSocial($redSocial, $comparison = null)
	{
		return $this
			->addUsingAlias(RedSocialXPerfilPeer::RED_SOCIAL_ID, $redSocial->getRedSocialId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the RedSocial relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    RedSocialXPerfilQuery The current query, for fluid interface
	 */
	public function joinRedSocial($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('RedSocial');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'RedSocial');
		}
		
		return $this;
	}

	/**
	 * Use the RedSocial relation RedSocial object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    RedSocialQuery A secondary query class using the current class as primary query
	 */
	public function useRedSocialQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinRedSocial($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'RedSocial', 'RedSocialQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     RedSocialXPerfil $redSocialXPerfil Object to remove from the list of results
	 *
	 * @return    RedSocialXPerfilQuery The current query, for fluid interface
	 */
	public function prune($redSocialXPerfil = null)
	{
		if ($redSocialXPerfil) {
			$this->addUsingAlias(RedSocialXPerfilPeer::RED_SOCIAL_X_PERFIL_ID, $redSocialXPerfil->getRedSocialXPerfilId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseRedSocialXPerfilQuery
