<?php


/**
 * Base class that represents a query for the 'blog_x_tematica' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Wed Dec  8 10:38:16 2010
 *
 * @method     BlogXTematicaQuery orderByBlogXTematicaId($order = Criteria::ASC) Order by the blog_x_tematica_id column
 * @method     BlogXTematicaQuery orderByBlogId($order = Criteria::ASC) Order by the blog_id column
 * @method     BlogXTematicaQuery orderByTematicaId($order = Criteria::ASC) Order by the tematica_id column
 *
 * @method     BlogXTematicaQuery groupByBlogXTematicaId() Group by the blog_x_tematica_id column
 * @method     BlogXTematicaQuery groupByBlogId() Group by the blog_id column
 * @method     BlogXTematicaQuery groupByTematicaId() Group by the tematica_id column
 *
 * @method     BlogXTematicaQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     BlogXTematicaQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     BlogXTematicaQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     BlogXTematicaQuery leftJoinBlog($relationAlias = null) Adds a LEFT JOIN clause to the query using the Blog relation
 * @method     BlogXTematicaQuery rightJoinBlog($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Blog relation
 * @method     BlogXTematicaQuery innerJoinBlog($relationAlias = null) Adds a INNER JOIN clause to the query using the Blog relation
 *
 * @method     BlogXTematicaQuery leftJoinTematica($relationAlias = null) Adds a LEFT JOIN clause to the query using the Tematica relation
 * @method     BlogXTematicaQuery rightJoinTematica($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Tematica relation
 * @method     BlogXTematicaQuery innerJoinTematica($relationAlias = null) Adds a INNER JOIN clause to the query using the Tematica relation
 *
 * @method     BlogXTematica findOne(PropelPDO $con = null) Return the first BlogXTematica matching the query
 * @method     BlogXTematica findOneOrCreate(PropelPDO $con = null) Return the first BlogXTematica matching the query, or a new BlogXTematica object populated from the query conditions when no match is found
 *
 * @method     BlogXTematica findOneByBlogXTematicaId(int $blog_x_tematica_id) Return the first BlogXTematica filtered by the blog_x_tematica_id column
 * @method     BlogXTematica findOneByBlogId(int $blog_id) Return the first BlogXTematica filtered by the blog_id column
 * @method     BlogXTematica findOneByTematicaId(int $tematica_id) Return the first BlogXTematica filtered by the tematica_id column
 *
 * @method     array findByBlogXTematicaId(int $blog_x_tematica_id) Return BlogXTematica objects filtered by the blog_x_tematica_id column
 * @method     array findByBlogId(int $blog_id) Return BlogXTematica objects filtered by the blog_id column
 * @method     array findByTematicaId(int $tematica_id) Return BlogXTematica objects filtered by the tematica_id column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseBlogXTematicaQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseBlogXTematicaQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'BlogXTematica', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new BlogXTematicaQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    BlogXTematicaQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof BlogXTematicaQuery) {
			return $criteria;
		}
		$query = new BlogXTematicaQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    BlogXTematica|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = BlogXTematicaPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    BlogXTematicaQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(BlogXTematicaPeer::BLOG_X_TEMATICA_ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    BlogXTematicaQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(BlogXTematicaPeer::BLOG_X_TEMATICA_ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the blog_x_tematica_id column
	 * 
	 * @param     int|array $blogXTematicaId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    BlogXTematicaQuery The current query, for fluid interface
	 */
	public function filterByBlogXTematicaId($blogXTematicaId = null, $comparison = null)
	{
		if (is_array($blogXTematicaId) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(BlogXTematicaPeer::BLOG_X_TEMATICA_ID, $blogXTematicaId, $comparison);
	}

	/**
	 * Filter the query on the blog_id column
	 * 
	 * @param     int|array $blogId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    BlogXTematicaQuery The current query, for fluid interface
	 */
	public function filterByBlogId($blogId = null, $comparison = null)
	{
		if (is_array($blogId)) {
			$useMinMax = false;
			if (isset($blogId['min'])) {
				$this->addUsingAlias(BlogXTematicaPeer::BLOG_ID, $blogId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($blogId['max'])) {
				$this->addUsingAlias(BlogXTematicaPeer::BLOG_ID, $blogId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(BlogXTematicaPeer::BLOG_ID, $blogId, $comparison);
	}

	/**
	 * Filter the query on the tematica_id column
	 * 
	 * @param     int|array $tematicaId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    BlogXTematicaQuery The current query, for fluid interface
	 */
	public function filterByTematicaId($tematicaId = null, $comparison = null)
	{
		if (is_array($tematicaId)) {
			$useMinMax = false;
			if (isset($tematicaId['min'])) {
				$this->addUsingAlias(BlogXTematicaPeer::TEMATICA_ID, $tematicaId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($tematicaId['max'])) {
				$this->addUsingAlias(BlogXTematicaPeer::TEMATICA_ID, $tematicaId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(BlogXTematicaPeer::TEMATICA_ID, $tematicaId, $comparison);
	}

	/**
	 * Filter the query by a related Blog object
	 *
	 * @param     Blog $blog  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    BlogXTematicaQuery The current query, for fluid interface
	 */
	public function filterByBlog($blog, $comparison = null)
	{
		return $this
			->addUsingAlias(BlogXTematicaPeer::BLOG_ID, $blog->getBlogId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the Blog relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    BlogXTematicaQuery The current query, for fluid interface
	 */
	public function joinBlog($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('Blog');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'Blog');
		}
		
		return $this;
	}

	/**
	 * Use the Blog relation Blog object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    BlogQuery A secondary query class using the current class as primary query
	 */
	public function useBlogQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinBlog($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'Blog', 'BlogQuery');
	}

	/**
	 * Filter the query by a related Tematica object
	 *
	 * @param     Tematica $tematica  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    BlogXTematicaQuery The current query, for fluid interface
	 */
	public function filterByTematica($tematica, $comparison = null)
	{
		return $this
			->addUsingAlias(BlogXTematicaPeer::TEMATICA_ID, $tematica->getTematicaId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the Tematica relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    BlogXTematicaQuery The current query, for fluid interface
	 */
	public function joinTematica($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('Tematica');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'Tematica');
		}
		
		return $this;
	}

	/**
	 * Use the Tematica relation Tematica object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    TematicaQuery A secondary query class using the current class as primary query
	 */
	public function useTematicaQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinTematica($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'Tematica', 'TematicaQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     BlogXTematica $blogXTematica Object to remove from the list of results
	 *
	 * @return    BlogXTematicaQuery The current query, for fluid interface
	 */
	public function prune($blogXTematica = null)
	{
		if ($blogXTematica) {
			$this->addUsingAlias(BlogXTematicaPeer::BLOG_X_TEMATICA_ID, $blogXTematica->getBlogXTematicaId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseBlogXTematicaQuery
