<?php


/**
 * Base class that represents a query for the 'tipo_post' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Wed Dec  8 10:38:16 2010
 *
 * @method     TipoPostQuery orderByTipoPostId($order = Criteria::ASC) Order by the tipo_post_id column
 * @method     TipoPostQuery orderByNombre($order = Criteria::ASC) Order by the nombre column
 * @method     TipoPostQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 *
 * @method     TipoPostQuery groupByTipoPostId() Group by the tipo_post_id column
 * @method     TipoPostQuery groupByNombre() Group by the nombre column
 * @method     TipoPostQuery groupByCreatedAt() Group by the created_at column
 *
 * @method     TipoPostQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     TipoPostQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     TipoPostQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     TipoPostQuery leftJoinPost($relationAlias = null) Adds a LEFT JOIN clause to the query using the Post relation
 * @method     TipoPostQuery rightJoinPost($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Post relation
 * @method     TipoPostQuery innerJoinPost($relationAlias = null) Adds a INNER JOIN clause to the query using the Post relation
 *
 * @method     TipoPost findOne(PropelPDO $con = null) Return the first TipoPost matching the query
 * @method     TipoPost findOneOrCreate(PropelPDO $con = null) Return the first TipoPost matching the query, or a new TipoPost object populated from the query conditions when no match is found
 *
 * @method     TipoPost findOneByTipoPostId(int $tipo_post_id) Return the first TipoPost filtered by the tipo_post_id column
 * @method     TipoPost findOneByNombre(string $nombre) Return the first TipoPost filtered by the nombre column
 * @method     TipoPost findOneByCreatedAt(string $created_at) Return the first TipoPost filtered by the created_at column
 *
 * @method     array findByTipoPostId(int $tipo_post_id) Return TipoPost objects filtered by the tipo_post_id column
 * @method     array findByNombre(string $nombre) Return TipoPost objects filtered by the nombre column
 * @method     array findByCreatedAt(string $created_at) Return TipoPost objects filtered by the created_at column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseTipoPostQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseTipoPostQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'TipoPost', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new TipoPostQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    TipoPostQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof TipoPostQuery) {
			return $criteria;
		}
		$query = new TipoPostQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    TipoPost|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = TipoPostPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    TipoPostQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(TipoPostPeer::TIPO_POST_ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    TipoPostQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(TipoPostPeer::TIPO_POST_ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the tipo_post_id column
	 * 
	 * @param     int|array $tipoPostId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TipoPostQuery The current query, for fluid interface
	 */
	public function filterByTipoPostId($tipoPostId = null, $comparison = null)
	{
		if (is_array($tipoPostId) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(TipoPostPeer::TIPO_POST_ID, $tipoPostId, $comparison);
	}

	/**
	 * Filter the query on the nombre column
	 * 
	 * @param     string $nombre The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TipoPostQuery The current query, for fluid interface
	 */
	public function filterByNombre($nombre = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($nombre)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $nombre)) {
				$nombre = str_replace('*', '%', $nombre);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(TipoPostPeer::NOMBRE, $nombre, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 * 
	 * @param     string|array $createdAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TipoPostQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(TipoPostPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(TipoPostPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(TipoPostPeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Filter the query by a related Post object
	 *
	 * @param     Post $post  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TipoPostQuery The current query, for fluid interface
	 */
	public function filterByPost($post, $comparison = null)
	{
		return $this
			->addUsingAlias(TipoPostPeer::TIPO_POST_ID, $post->getTipoPostId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the Post relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    TipoPostQuery The current query, for fluid interface
	 */
	public function joinPost($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('Post');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'Post');
		}
		
		return $this;
	}

	/**
	 * Use the Post relation Post object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    PostQuery A secondary query class using the current class as primary query
	 */
	public function usePostQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinPost($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'Post', 'PostQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     TipoPost $tipoPost Object to remove from the list of results
	 *
	 * @return    TipoPostQuery The current query, for fluid interface
	 */
	public function prune($tipoPost = null)
	{
		if ($tipoPost) {
			$this->addUsingAlias(TipoPostPeer::TIPO_POST_ID, $tipoPost->getTipoPostId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseTipoPostQuery
