<?php


/**
 * Base class that represents a query for the 'mensaje' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Wed Dec  8 10:38:15 2010
 *
 * @method     MensajeQuery orderByMensajeId($order = Criteria::ASC) Order by the mensaje_id column
 * @method     MensajeQuery orderByDestinatarioId($order = Criteria::ASC) Order by the destinatario_id column
 * @method     MensajeQuery orderByRemitenteId($order = Criteria::ASC) Order by the remitente_id column
 * @method     MensajeQuery orderByAnonimo($order = Criteria::ASC) Order by the anonimo column
 * @method     MensajeQuery orderByAsunto($order = Criteria::ASC) Order by the asunto column
 * @method     MensajeQuery orderByMensaje($order = Criteria::ASC) Order by the mensaje column
 * @method     MensajeQuery orderBySendAt($order = Criteria::ASC) Order by the send_at column
 * @method     MensajeQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 *
 * @method     MensajeQuery groupByMensajeId() Group by the mensaje_id column
 * @method     MensajeQuery groupByDestinatarioId() Group by the destinatario_id column
 * @method     MensajeQuery groupByRemitenteId() Group by the remitente_id column
 * @method     MensajeQuery groupByAnonimo() Group by the anonimo column
 * @method     MensajeQuery groupByAsunto() Group by the asunto column
 * @method     MensajeQuery groupByMensaje() Group by the mensaje column
 * @method     MensajeQuery groupBySendAt() Group by the send_at column
 * @method     MensajeQuery groupByCreatedAt() Group by the created_at column
 *
 * @method     MensajeQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     MensajeQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     MensajeQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     MensajeQuery leftJoinsfGuardUserRelatedByDestinatarioId($relationAlias = null) Adds a LEFT JOIN clause to the query using the sfGuardUserRelatedByDestinatarioId relation
 * @method     MensajeQuery rightJoinsfGuardUserRelatedByDestinatarioId($relationAlias = null) Adds a RIGHT JOIN clause to the query using the sfGuardUserRelatedByDestinatarioId relation
 * @method     MensajeQuery innerJoinsfGuardUserRelatedByDestinatarioId($relationAlias = null) Adds a INNER JOIN clause to the query using the sfGuardUserRelatedByDestinatarioId relation
 *
 * @method     MensajeQuery leftJoinsfGuardUserRelatedByRemitenteId($relationAlias = null) Adds a LEFT JOIN clause to the query using the sfGuardUserRelatedByRemitenteId relation
 * @method     MensajeQuery rightJoinsfGuardUserRelatedByRemitenteId($relationAlias = null) Adds a RIGHT JOIN clause to the query using the sfGuardUserRelatedByRemitenteId relation
 * @method     MensajeQuery innerJoinsfGuardUserRelatedByRemitenteId($relationAlias = null) Adds a INNER JOIN clause to the query using the sfGuardUserRelatedByRemitenteId relation
 *
 * @method     MensajeQuery leftJoinRespuestaMensaje($relationAlias = null) Adds a LEFT JOIN clause to the query using the RespuestaMensaje relation
 * @method     MensajeQuery rightJoinRespuestaMensaje($relationAlias = null) Adds a RIGHT JOIN clause to the query using the RespuestaMensaje relation
 * @method     MensajeQuery innerJoinRespuestaMensaje($relationAlias = null) Adds a INNER JOIN clause to the query using the RespuestaMensaje relation
 *
 * @method     Mensaje findOne(PropelPDO $con = null) Return the first Mensaje matching the query
 * @method     Mensaje findOneOrCreate(PropelPDO $con = null) Return the first Mensaje matching the query, or a new Mensaje object populated from the query conditions when no match is found
 *
 * @method     Mensaje findOneByMensajeId(int $mensaje_id) Return the first Mensaje filtered by the mensaje_id column
 * @method     Mensaje findOneByDestinatarioId(int $destinatario_id) Return the first Mensaje filtered by the destinatario_id column
 * @method     Mensaje findOneByRemitenteId(int $remitente_id) Return the first Mensaje filtered by the remitente_id column
 * @method     Mensaje findOneByAnonimo(int $anonimo) Return the first Mensaje filtered by the anonimo column
 * @method     Mensaje findOneByAsunto(string $asunto) Return the first Mensaje filtered by the asunto column
 * @method     Mensaje findOneByMensaje(string $mensaje) Return the first Mensaje filtered by the mensaje column
 * @method     Mensaje findOneBySendAt(string $send_at) Return the first Mensaje filtered by the send_at column
 * @method     Mensaje findOneByCreatedAt(string $created_at) Return the first Mensaje filtered by the created_at column
 *
 * @method     array findByMensajeId(int $mensaje_id) Return Mensaje objects filtered by the mensaje_id column
 * @method     array findByDestinatarioId(int $destinatario_id) Return Mensaje objects filtered by the destinatario_id column
 * @method     array findByRemitenteId(int $remitente_id) Return Mensaje objects filtered by the remitente_id column
 * @method     array findByAnonimo(int $anonimo) Return Mensaje objects filtered by the anonimo column
 * @method     array findByAsunto(string $asunto) Return Mensaje objects filtered by the asunto column
 * @method     array findByMensaje(string $mensaje) Return Mensaje objects filtered by the mensaje column
 * @method     array findBySendAt(string $send_at) Return Mensaje objects filtered by the send_at column
 * @method     array findByCreatedAt(string $created_at) Return Mensaje objects filtered by the created_at column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseMensajeQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseMensajeQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'Mensaje', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new MensajeQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    MensajeQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof MensajeQuery) {
			return $criteria;
		}
		$query = new MensajeQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    Mensaje|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = MensajePeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(MensajePeer::MENSAJE_ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(MensajePeer::MENSAJE_ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the mensaje_id column
	 * 
	 * @param     int|array $mensajeId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function filterByMensajeId($mensajeId = null, $comparison = null)
	{
		if (is_array($mensajeId) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(MensajePeer::MENSAJE_ID, $mensajeId, $comparison);
	}

	/**
	 * Filter the query on the destinatario_id column
	 * 
	 * @param     int|array $destinatarioId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function filterByDestinatarioId($destinatarioId = null, $comparison = null)
	{
		if (is_array($destinatarioId)) {
			$useMinMax = false;
			if (isset($destinatarioId['min'])) {
				$this->addUsingAlias(MensajePeer::DESTINATARIO_ID, $destinatarioId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($destinatarioId['max'])) {
				$this->addUsingAlias(MensajePeer::DESTINATARIO_ID, $destinatarioId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(MensajePeer::DESTINATARIO_ID, $destinatarioId, $comparison);
	}

	/**
	 * Filter the query on the remitente_id column
	 * 
	 * @param     int|array $remitenteId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function filterByRemitenteId($remitenteId = null, $comparison = null)
	{
		if (is_array($remitenteId)) {
			$useMinMax = false;
			if (isset($remitenteId['min'])) {
				$this->addUsingAlias(MensajePeer::REMITENTE_ID, $remitenteId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($remitenteId['max'])) {
				$this->addUsingAlias(MensajePeer::REMITENTE_ID, $remitenteId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(MensajePeer::REMITENTE_ID, $remitenteId, $comparison);
	}

	/**
	 * Filter the query on the anonimo column
	 * 
	 * @param     int|array $anonimo The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function filterByAnonimo($anonimo = null, $comparison = null)
	{
		if (is_array($anonimo)) {
			$useMinMax = false;
			if (isset($anonimo['min'])) {
				$this->addUsingAlias(MensajePeer::ANONIMO, $anonimo['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($anonimo['max'])) {
				$this->addUsingAlias(MensajePeer::ANONIMO, $anonimo['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(MensajePeer::ANONIMO, $anonimo, $comparison);
	}

	/**
	 * Filter the query on the asunto column
	 * 
	 * @param     string $asunto The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function filterByAsunto($asunto = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($asunto)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $asunto)) {
				$asunto = str_replace('*', '%', $asunto);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MensajePeer::ASUNTO, $asunto, $comparison);
	}

	/**
	 * Filter the query on the mensaje column
	 * 
	 * @param     string $mensaje The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function filterByMensaje($mensaje = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($mensaje)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $mensaje)) {
				$mensaje = str_replace('*', '%', $mensaje);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MensajePeer::MENSAJE, $mensaje, $comparison);
	}

	/**
	 * Filter the query on the send_at column
	 * 
	 * @param     string|array $sendAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function filterBySendAt($sendAt = null, $comparison = null)
	{
		if (is_array($sendAt)) {
			$useMinMax = false;
			if (isset($sendAt['min'])) {
				$this->addUsingAlias(MensajePeer::SEND_AT, $sendAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($sendAt['max'])) {
				$this->addUsingAlias(MensajePeer::SEND_AT, $sendAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(MensajePeer::SEND_AT, $sendAt, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 * 
	 * @param     string|array $createdAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(MensajePeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(MensajePeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(MensajePeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Filter the query by a related sfGuardUser object
	 *
	 * @param     sfGuardUser $sfGuardUser  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function filterBysfGuardUserRelatedByDestinatarioId($sfGuardUser, $comparison = null)
	{
		return $this
			->addUsingAlias(MensajePeer::DESTINATARIO_ID, $sfGuardUser->getId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the sfGuardUserRelatedByDestinatarioId relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function joinsfGuardUserRelatedByDestinatarioId($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('sfGuardUserRelatedByDestinatarioId');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'sfGuardUserRelatedByDestinatarioId');
		}
		
		return $this;
	}

	/**
	 * Use the sfGuardUserRelatedByDestinatarioId relation sfGuardUser object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfGuardUserQuery A secondary query class using the current class as primary query
	 */
	public function usesfGuardUserRelatedByDestinatarioIdQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinsfGuardUserRelatedByDestinatarioId($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'sfGuardUserRelatedByDestinatarioId', 'sfGuardUserQuery');
	}

	/**
	 * Filter the query by a related sfGuardUser object
	 *
	 * @param     sfGuardUser $sfGuardUser  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function filterBysfGuardUserRelatedByRemitenteId($sfGuardUser, $comparison = null)
	{
		return $this
			->addUsingAlias(MensajePeer::REMITENTE_ID, $sfGuardUser->getId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the sfGuardUserRelatedByRemitenteId relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function joinsfGuardUserRelatedByRemitenteId($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('sfGuardUserRelatedByRemitenteId');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'sfGuardUserRelatedByRemitenteId');
		}
		
		return $this;
	}

	/**
	 * Use the sfGuardUserRelatedByRemitenteId relation sfGuardUser object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    sfGuardUserQuery A secondary query class using the current class as primary query
	 */
	public function usesfGuardUserRelatedByRemitenteIdQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinsfGuardUserRelatedByRemitenteId($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'sfGuardUserRelatedByRemitenteId', 'sfGuardUserQuery');
	}

	/**
	 * Filter the query by a related RespuestaMensaje object
	 *
	 * @param     RespuestaMensaje $respuestaMensaje  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function filterByRespuestaMensaje($respuestaMensaje, $comparison = null)
	{
		return $this
			->addUsingAlias(MensajePeer::MENSAJE_ID, $respuestaMensaje->getMensajeId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the RespuestaMensaje relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function joinRespuestaMensaje($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('RespuestaMensaje');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'RespuestaMensaje');
		}
		
		return $this;
	}

	/**
	 * Use the RespuestaMensaje relation RespuestaMensaje object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    RespuestaMensajeQuery A secondary query class using the current class as primary query
	 */
	public function useRespuestaMensajeQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinRespuestaMensaje($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'RespuestaMensaje', 'RespuestaMensajeQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     Mensaje $mensaje Object to remove from the list of results
	 *
	 * @return    MensajeQuery The current query, for fluid interface
	 */
	public function prune($mensaje = null)
	{
		if ($mensaje) {
			$this->addUsingAlias(MensajePeer::MENSAJE_ID, $mensaje->getMensajeId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseMensajeQuery
