<?php


/**
 * Base class that represents a query for the 'boletin' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Wed Dec  8 10:38:17 2010
 *
 * @method     BoletinQuery orderByBoletinId($order = Criteria::ASC) Order by the boletin_id column
 * @method     BoletinQuery orderByBlogId($order = Criteria::ASC) Order by the blog_id column
 * @method     BoletinQuery orderByNombre($order = Criteria::ASC) Order by the nombre column
 * @method     BoletinQuery orderBySendAt($order = Criteria::ASC) Order by the send_at column
 * @method     BoletinQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 *
 * @method     BoletinQuery groupByBoletinId() Group by the boletin_id column
 * @method     BoletinQuery groupByBlogId() Group by the blog_id column
 * @method     BoletinQuery groupByNombre() Group by the nombre column
 * @method     BoletinQuery groupBySendAt() Group by the send_at column
 * @method     BoletinQuery groupByCreatedAt() Group by the created_at column
 *
 * @method     BoletinQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     BoletinQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     BoletinQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     BoletinQuery leftJoinBlog($relationAlias = null) Adds a LEFT JOIN clause to the query using the Blog relation
 * @method     BoletinQuery rightJoinBlog($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Blog relation
 * @method     BoletinQuery innerJoinBlog($relationAlias = null) Adds a INNER JOIN clause to the query using the Blog relation
 *
 * @method     BoletinQuery leftJoinNotasBoletin($relationAlias = null) Adds a LEFT JOIN clause to the query using the NotasBoletin relation
 * @method     BoletinQuery rightJoinNotasBoletin($relationAlias = null) Adds a RIGHT JOIN clause to the query using the NotasBoletin relation
 * @method     BoletinQuery innerJoinNotasBoletin($relationAlias = null) Adds a INNER JOIN clause to the query using the NotasBoletin relation
 *
 * @method     Boletin findOne(PropelPDO $con = null) Return the first Boletin matching the query
 * @method     Boletin findOneOrCreate(PropelPDO $con = null) Return the first Boletin matching the query, or a new Boletin object populated from the query conditions when no match is found
 *
 * @method     Boletin findOneByBoletinId(int $boletin_id) Return the first Boletin filtered by the boletin_id column
 * @method     Boletin findOneByBlogId(int $blog_id) Return the first Boletin filtered by the blog_id column
 * @method     Boletin findOneByNombre(string $nombre) Return the first Boletin filtered by the nombre column
 * @method     Boletin findOneBySendAt(string $send_at) Return the first Boletin filtered by the send_at column
 * @method     Boletin findOneByCreatedAt(string $created_at) Return the first Boletin filtered by the created_at column
 *
 * @method     array findByBoletinId(int $boletin_id) Return Boletin objects filtered by the boletin_id column
 * @method     array findByBlogId(int $blog_id) Return Boletin objects filtered by the blog_id column
 * @method     array findByNombre(string $nombre) Return Boletin objects filtered by the nombre column
 * @method     array findBySendAt(string $send_at) Return Boletin objects filtered by the send_at column
 * @method     array findByCreatedAt(string $created_at) Return Boletin objects filtered by the created_at column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseBoletinQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseBoletinQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'Boletin', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new BoletinQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    BoletinQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof BoletinQuery) {
			return $criteria;
		}
		$query = new BoletinQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    Boletin|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = BoletinPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    BoletinQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(BoletinPeer::BOLETIN_ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    BoletinQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(BoletinPeer::BOLETIN_ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the boletin_id column
	 * 
	 * @param     int|array $boletinId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    BoletinQuery The current query, for fluid interface
	 */
	public function filterByBoletinId($boletinId = null, $comparison = null)
	{
		if (is_array($boletinId) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(BoletinPeer::BOLETIN_ID, $boletinId, $comparison);
	}

	/**
	 * Filter the query on the blog_id column
	 * 
	 * @param     int|array $blogId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    BoletinQuery The current query, for fluid interface
	 */
	public function filterByBlogId($blogId = null, $comparison = null)
	{
		if (is_array($blogId)) {
			$useMinMax = false;
			if (isset($blogId['min'])) {
				$this->addUsingAlias(BoletinPeer::BLOG_ID, $blogId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($blogId['max'])) {
				$this->addUsingAlias(BoletinPeer::BLOG_ID, $blogId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(BoletinPeer::BLOG_ID, $blogId, $comparison);
	}

	/**
	 * Filter the query on the nombre column
	 * 
	 * @param     string $nombre The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    BoletinQuery The current query, for fluid interface
	 */
	public function filterByNombre($nombre = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($nombre)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $nombre)) {
				$nombre = str_replace('*', '%', $nombre);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(BoletinPeer::NOMBRE, $nombre, $comparison);
	}

	/**
	 * Filter the query on the send_at column
	 * 
	 * @param     string|array $sendAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    BoletinQuery The current query, for fluid interface
	 */
	public function filterBySendAt($sendAt = null, $comparison = null)
	{
		if (is_array($sendAt)) {
			$useMinMax = false;
			if (isset($sendAt['min'])) {
				$this->addUsingAlias(BoletinPeer::SEND_AT, $sendAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($sendAt['max'])) {
				$this->addUsingAlias(BoletinPeer::SEND_AT, $sendAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(BoletinPeer::SEND_AT, $sendAt, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 * 
	 * @param     string|array $createdAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    BoletinQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(BoletinPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(BoletinPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(BoletinPeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Filter the query by a related Blog object
	 *
	 * @param     Blog $blog  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    BoletinQuery The current query, for fluid interface
	 */
	public function filterByBlog($blog, $comparison = null)
	{
		return $this
			->addUsingAlias(BoletinPeer::BLOG_ID, $blog->getBlogId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the Blog relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    BoletinQuery The current query, for fluid interface
	 */
	public function joinBlog($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('Blog');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'Blog');
		}
		
		return $this;
	}

	/**
	 * Use the Blog relation Blog object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    BlogQuery A secondary query class using the current class as primary query
	 */
	public function useBlogQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinBlog($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'Blog', 'BlogQuery');
	}

	/**
	 * Filter the query by a related NotasBoletin object
	 *
	 * @param     NotasBoletin $notasBoletin  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    BoletinQuery The current query, for fluid interface
	 */
	public function filterByNotasBoletin($notasBoletin, $comparison = null)
	{
		return $this
			->addUsingAlias(BoletinPeer::BOLETIN_ID, $notasBoletin->getBoletinId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the NotasBoletin relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    BoletinQuery The current query, for fluid interface
	 */
	public function joinNotasBoletin($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('NotasBoletin');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'NotasBoletin');
		}
		
		return $this;
	}

	/**
	 * Use the NotasBoletin relation NotasBoletin object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    NotasBoletinQuery A secondary query class using the current class as primary query
	 */
	public function useNotasBoletinQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinNotasBoletin($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'NotasBoletin', 'NotasBoletinQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     Boletin $boletin Object to remove from the list of results
	 *
	 * @return    BoletinQuery The current query, for fluid interface
	 */
	public function prune($boletin = null)
	{
		if ($boletin) {
			$this->addUsingAlias(BoletinPeer::BOLETIN_ID, $boletin->getBoletinId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseBoletinQuery
