<?php


/**
 * Base class that represents a query for the 'anonimo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Wed Dec  8 10:38:14 2010
 *
 * @method     AnonimoQuery orderByAnonimoId($order = Criteria::ASC) Order by the anonimo_id column
 * @method     AnonimoQuery orderByNombre($order = Criteria::ASC) Order by the nombre column
 * @method     AnonimoQuery orderByEmail($order = Criteria::ASC) Order by the email column
 * @method     AnonimoQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 *
 * @method     AnonimoQuery groupByAnonimoId() Group by the anonimo_id column
 * @method     AnonimoQuery groupByNombre() Group by the nombre column
 * @method     AnonimoQuery groupByEmail() Group by the email column
 * @method     AnonimoQuery groupByCreatedAt() Group by the created_at column
 *
 * @method     AnonimoQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     AnonimoQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     AnonimoQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     Anonimo findOne(PropelPDO $con = null) Return the first Anonimo matching the query
 * @method     Anonimo findOneOrCreate(PropelPDO $con = null) Return the first Anonimo matching the query, or a new Anonimo object populated from the query conditions when no match is found
 *
 * @method     Anonimo findOneByAnonimoId(int $anonimo_id) Return the first Anonimo filtered by the anonimo_id column
 * @method     Anonimo findOneByNombre(string $nombre) Return the first Anonimo filtered by the nombre column
 * @method     Anonimo findOneByEmail(string $email) Return the first Anonimo filtered by the email column
 * @method     Anonimo findOneByCreatedAt(string $created_at) Return the first Anonimo filtered by the created_at column
 *
 * @method     array findByAnonimoId(int $anonimo_id) Return Anonimo objects filtered by the anonimo_id column
 * @method     array findByNombre(string $nombre) Return Anonimo objects filtered by the nombre column
 * @method     array findByEmail(string $email) Return Anonimo objects filtered by the email column
 * @method     array findByCreatedAt(string $created_at) Return Anonimo objects filtered by the created_at column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseAnonimoQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseAnonimoQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'Anonimo', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new AnonimoQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    AnonimoQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof AnonimoQuery) {
			return $criteria;
		}
		$query = new AnonimoQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    Anonimo|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = AnonimoPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    AnonimoQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(AnonimoPeer::ANONIMO_ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    AnonimoQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(AnonimoPeer::ANONIMO_ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the anonimo_id column
	 * 
	 * @param     int|array $anonimoId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    AnonimoQuery The current query, for fluid interface
	 */
	public function filterByAnonimoId($anonimoId = null, $comparison = null)
	{
		if (is_array($anonimoId) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(AnonimoPeer::ANONIMO_ID, $anonimoId, $comparison);
	}

	/**
	 * Filter the query on the nombre column
	 * 
	 * @param     string $nombre The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    AnonimoQuery The current query, for fluid interface
	 */
	public function filterByNombre($nombre = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($nombre)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $nombre)) {
				$nombre = str_replace('*', '%', $nombre);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(AnonimoPeer::NOMBRE, $nombre, $comparison);
	}

	/**
	 * Filter the query on the email column
	 * 
	 * @param     string $email The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    AnonimoQuery The current query, for fluid interface
	 */
	public function filterByEmail($email = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($email)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $email)) {
				$email = str_replace('*', '%', $email);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(AnonimoPeer::EMAIL, $email, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 * 
	 * @param     string|array $createdAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    AnonimoQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(AnonimoPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(AnonimoPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(AnonimoPeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Exclude object from result
	 *
	 * @param     Anonimo $anonimo Object to remove from the list of results
	 *
	 * @return    AnonimoQuery The current query, for fluid interface
	 */
	public function prune($anonimo = null)
	{
		if ($anonimo) {
			$this->addUsingAlias(AnonimoPeer::ANONIMO_ID, $anonimo->getAnonimoId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseAnonimoQuery
