<?php


/**
 * Base class that represents a query for the 'respuesta' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Wed Dec  8 10:38:17 2010
 *
 * @method     RespuestaQuery orderByRespuestaId($order = Criteria::ASC) Order by the respuesta_id column
 * @method     RespuestaQuery orderByPostId($order = Criteria::ASC) Order by the post_id column
 * @method     RespuestaQuery orderByOpcion($order = Criteria::ASC) Order by the opcion column
 * @method     RespuestaQuery orderByCantidad($order = Criteria::ASC) Order by the cantidad column
 * @method     RespuestaQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 *
 * @method     RespuestaQuery groupByRespuestaId() Group by the respuesta_id column
 * @method     RespuestaQuery groupByPostId() Group by the post_id column
 * @method     RespuestaQuery groupByOpcion() Group by the opcion column
 * @method     RespuestaQuery groupByCantidad() Group by the cantidad column
 * @method     RespuestaQuery groupByCreatedAt() Group by the created_at column
 *
 * @method     RespuestaQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     RespuestaQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     RespuestaQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     RespuestaQuery leftJoinPost($relationAlias = null) Adds a LEFT JOIN clause to the query using the Post relation
 * @method     RespuestaQuery rightJoinPost($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Post relation
 * @method     RespuestaQuery innerJoinPost($relationAlias = null) Adds a INNER JOIN clause to the query using the Post relation
 *
 * @method     Respuesta findOne(PropelPDO $con = null) Return the first Respuesta matching the query
 * @method     Respuesta findOneOrCreate(PropelPDO $con = null) Return the first Respuesta matching the query, or a new Respuesta object populated from the query conditions when no match is found
 *
 * @method     Respuesta findOneByRespuestaId(int $respuesta_id) Return the first Respuesta filtered by the respuesta_id column
 * @method     Respuesta findOneByPostId(int $post_id) Return the first Respuesta filtered by the post_id column
 * @method     Respuesta findOneByOpcion(string $opcion) Return the first Respuesta filtered by the opcion column
 * @method     Respuesta findOneByCantidad(string $cantidad) Return the first Respuesta filtered by the cantidad column
 * @method     Respuesta findOneByCreatedAt(string $created_at) Return the first Respuesta filtered by the created_at column
 *
 * @method     array findByRespuestaId(int $respuesta_id) Return Respuesta objects filtered by the respuesta_id column
 * @method     array findByPostId(int $post_id) Return Respuesta objects filtered by the post_id column
 * @method     array findByOpcion(string $opcion) Return Respuesta objects filtered by the opcion column
 * @method     array findByCantidad(string $cantidad) Return Respuesta objects filtered by the cantidad column
 * @method     array findByCreatedAt(string $created_at) Return Respuesta objects filtered by the created_at column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseRespuestaQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseRespuestaQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'Respuesta', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new RespuestaQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    RespuestaQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof RespuestaQuery) {
			return $criteria;
		}
		$query = new RespuestaQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    Respuesta|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = RespuestaPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    RespuestaQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(RespuestaPeer::RESPUESTA_ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    RespuestaQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(RespuestaPeer::RESPUESTA_ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the respuesta_id column
	 * 
	 * @param     int|array $respuestaId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RespuestaQuery The current query, for fluid interface
	 */
	public function filterByRespuestaId($respuestaId = null, $comparison = null)
	{
		if (is_array($respuestaId) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(RespuestaPeer::RESPUESTA_ID, $respuestaId, $comparison);
	}

	/**
	 * Filter the query on the post_id column
	 * 
	 * @param     int|array $postId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RespuestaQuery The current query, for fluid interface
	 */
	public function filterByPostId($postId = null, $comparison = null)
	{
		if (is_array($postId)) {
			$useMinMax = false;
			if (isset($postId['min'])) {
				$this->addUsingAlias(RespuestaPeer::POST_ID, $postId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($postId['max'])) {
				$this->addUsingAlias(RespuestaPeer::POST_ID, $postId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(RespuestaPeer::POST_ID, $postId, $comparison);
	}

	/**
	 * Filter the query on the opcion column
	 * 
	 * @param     string $opcion The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RespuestaQuery The current query, for fluid interface
	 */
	public function filterByOpcion($opcion = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($opcion)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $opcion)) {
				$opcion = str_replace('*', '%', $opcion);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(RespuestaPeer::OPCION, $opcion, $comparison);
	}

	/**
	 * Filter the query on the cantidad column
	 * 
	 * @param     string $cantidad The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RespuestaQuery The current query, for fluid interface
	 */
	public function filterByCantidad($cantidad = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($cantidad)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $cantidad)) {
				$cantidad = str_replace('*', '%', $cantidad);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(RespuestaPeer::CANTIDAD, $cantidad, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 * 
	 * @param     string|array $createdAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RespuestaQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(RespuestaPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(RespuestaPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(RespuestaPeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Filter the query by a related Post object
	 *
	 * @param     Post $post  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RespuestaQuery The current query, for fluid interface
	 */
	public function filterByPost($post, $comparison = null)
	{
		return $this
			->addUsingAlias(RespuestaPeer::POST_ID, $post->getPostId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the Post relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    RespuestaQuery The current query, for fluid interface
	 */
	public function joinPost($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('Post');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'Post');
		}
		
		return $this;
	}

	/**
	 * Use the Post relation Post object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    PostQuery A secondary query class using the current class as primary query
	 */
	public function usePostQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinPost($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'Post', 'PostQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     Respuesta $respuesta Object to remove from the list of results
	 *
	 * @return    RespuestaQuery The current query, for fluid interface
	 */
	public function prune($respuesta = null)
	{
		if ($respuesta) {
			$this->addUsingAlias(RespuestaPeer::RESPUESTA_ID, $respuesta->getRespuestaId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseRespuestaQuery
