<?php


/**
 * Base class that represents a query for the 'respuesta_mensaje' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Wed Dec  8 10:38:15 2010
 *
 * @method     RespuestaMensajeQuery orderByRespuestaMensajeId($order = Criteria::ASC) Order by the respuesta_mensaje_id column
 * @method     RespuestaMensajeQuery orderByMensajeId($order = Criteria::ASC) Order by the mensaje_id column
 * @method     RespuestaMensajeQuery orderByCuerpo($order = Criteria::ASC) Order by the cuerpo column
 * @method     RespuestaMensajeQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 *
 * @method     RespuestaMensajeQuery groupByRespuestaMensajeId() Group by the respuesta_mensaje_id column
 * @method     RespuestaMensajeQuery groupByMensajeId() Group by the mensaje_id column
 * @method     RespuestaMensajeQuery groupByCuerpo() Group by the cuerpo column
 * @method     RespuestaMensajeQuery groupByCreatedAt() Group by the created_at column
 *
 * @method     RespuestaMensajeQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     RespuestaMensajeQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     RespuestaMensajeQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     RespuestaMensajeQuery leftJoinMensaje($relationAlias = null) Adds a LEFT JOIN clause to the query using the Mensaje relation
 * @method     RespuestaMensajeQuery rightJoinMensaje($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Mensaje relation
 * @method     RespuestaMensajeQuery innerJoinMensaje($relationAlias = null) Adds a INNER JOIN clause to the query using the Mensaje relation
 *
 * @method     RespuestaMensaje findOne(PropelPDO $con = null) Return the first RespuestaMensaje matching the query
 * @method     RespuestaMensaje findOneOrCreate(PropelPDO $con = null) Return the first RespuestaMensaje matching the query, or a new RespuestaMensaje object populated from the query conditions when no match is found
 *
 * @method     RespuestaMensaje findOneByRespuestaMensajeId(int $respuesta_mensaje_id) Return the first RespuestaMensaje filtered by the respuesta_mensaje_id column
 * @method     RespuestaMensaje findOneByMensajeId(int $mensaje_id) Return the first RespuestaMensaje filtered by the mensaje_id column
 * @method     RespuestaMensaje findOneByCuerpo(string $cuerpo) Return the first RespuestaMensaje filtered by the cuerpo column
 * @method     RespuestaMensaje findOneByCreatedAt(string $created_at) Return the first RespuestaMensaje filtered by the created_at column
 *
 * @method     array findByRespuestaMensajeId(int $respuesta_mensaje_id) Return RespuestaMensaje objects filtered by the respuesta_mensaje_id column
 * @method     array findByMensajeId(int $mensaje_id) Return RespuestaMensaje objects filtered by the mensaje_id column
 * @method     array findByCuerpo(string $cuerpo) Return RespuestaMensaje objects filtered by the cuerpo column
 * @method     array findByCreatedAt(string $created_at) Return RespuestaMensaje objects filtered by the created_at column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseRespuestaMensajeQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseRespuestaMensajeQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'RespuestaMensaje', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new RespuestaMensajeQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    RespuestaMensajeQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof RespuestaMensajeQuery) {
			return $criteria;
		}
		$query = new RespuestaMensajeQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    RespuestaMensaje|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = RespuestaMensajePeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    RespuestaMensajeQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(RespuestaMensajePeer::RESPUESTA_MENSAJE_ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    RespuestaMensajeQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(RespuestaMensajePeer::RESPUESTA_MENSAJE_ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the respuesta_mensaje_id column
	 * 
	 * @param     int|array $respuestaMensajeId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RespuestaMensajeQuery The current query, for fluid interface
	 */
	public function filterByRespuestaMensajeId($respuestaMensajeId = null, $comparison = null)
	{
		if (is_array($respuestaMensajeId) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(RespuestaMensajePeer::RESPUESTA_MENSAJE_ID, $respuestaMensajeId, $comparison);
	}

	/**
	 * Filter the query on the mensaje_id column
	 * 
	 * @param     int|array $mensajeId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RespuestaMensajeQuery The current query, for fluid interface
	 */
	public function filterByMensajeId($mensajeId = null, $comparison = null)
	{
		if (is_array($mensajeId)) {
			$useMinMax = false;
			if (isset($mensajeId['min'])) {
				$this->addUsingAlias(RespuestaMensajePeer::MENSAJE_ID, $mensajeId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($mensajeId['max'])) {
				$this->addUsingAlias(RespuestaMensajePeer::MENSAJE_ID, $mensajeId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(RespuestaMensajePeer::MENSAJE_ID, $mensajeId, $comparison);
	}

	/**
	 * Filter the query on the cuerpo column
	 * 
	 * @param     string $cuerpo The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RespuestaMensajeQuery The current query, for fluid interface
	 */
	public function filterByCuerpo($cuerpo = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($cuerpo)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $cuerpo)) {
				$cuerpo = str_replace('*', '%', $cuerpo);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(RespuestaMensajePeer::CUERPO, $cuerpo, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 * 
	 * @param     string|array $createdAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RespuestaMensajeQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(RespuestaMensajePeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(RespuestaMensajePeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(RespuestaMensajePeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Filter the query by a related Mensaje object
	 *
	 * @param     Mensaje $mensaje  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    RespuestaMensajeQuery The current query, for fluid interface
	 */
	public function filterByMensaje($mensaje, $comparison = null)
	{
		return $this
			->addUsingAlias(RespuestaMensajePeer::MENSAJE_ID, $mensaje->getMensajeId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the Mensaje relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    RespuestaMensajeQuery The current query, for fluid interface
	 */
	public function joinMensaje($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('Mensaje');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'Mensaje');
		}
		
		return $this;
	}

	/**
	 * Use the Mensaje relation Mensaje object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MensajeQuery A secondary query class using the current class as primary query
	 */
	public function useMensajeQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinMensaje($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'Mensaje', 'MensajeQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     RespuestaMensaje $respuestaMensaje Object to remove from the list of results
	 *
	 * @return    RespuestaMensajeQuery The current query, for fluid interface
	 */
	public function prune($respuestaMensaje = null)
	{
		if ($respuestaMensaje) {
			$this->addUsingAlias(RespuestaMensajePeer::RESPUESTA_MENSAJE_ID, $respuestaMensaje->getRespuestaMensajeId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseRespuestaMensajeQuery
