<?php


/**
 * Skeleton subclass for representing a row from the 'anonimo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Dec  5 22:01:17 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Anonimo extends BaseAnonimo {

} // Anonimo
