<?php


/**
 * Skeleton subclass for performing query and update operations on the 'blog_x_tematica' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Dec  5 22:01:23 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class BlogXTematicaPeer extends BaseBlogXTematicaPeer {

} // BlogXTematicaPeer
